Repository BrightCoders-Institute/BCDIC22-RN-reservacion-vuelos-team4, pull requests merged in 2023-02, with the labels that each got.

#40 feature#31-(Design)-Create-screens-reservations
  package-lock.json
  package.json
  src/components/BookingInputs.jsx
  src/components/CalendarBooking.jsx
  src/navigation/index.jsx
  src/theme/StyleBooking.jsx
  src/theme/StyleBookingInputs.jsx
  src/theme/colors.jsx
  src/views/Bookings/From.jsx
  src/views/Bookings/Passenger.jsx
  src/views/Bookings/Results.jsx
  src/views/Bookings/SelectDate.jsx
  src/views/Bookings/To.jsx
Labels: @QuackDuster

#46 feature#42-Display-information-on-My-flights-screen
  src/views/MyFlights.jsx
Labels: @Zuack55

#45 feature#41-New-flights-collection
  src/components/CalendarBooking.jsx
  src/components/FloatingButton.jsx
  src/components/WheelScrollPicker.jsx
  src/db/firebaseConfig.js
  src/navigation/index.jsx
  src/views/Bookings/From.jsx
  src/views/Bookings/Passenger.jsx
  src/views/Bookings/Results.jsx
  src/views/Bookings/SelectDate.jsx
  src/views/Bookings/To.jsx
  src/views/SignUp.jsx
Labels: @Zuack55

#47 feature#44-Back and logout buttons
  src/views/Bookings/From.jsx
  src/views/Bookings/Passenger.jsx
  src/views/Bookings/Results.jsx
  src/views/Bookings/SelectDate.jsx
  src/views/Bookings/To.jsx
  src/views/Login.jsx
  src/views/MyFlights.jsx
Labels: @Zuack55

#48 feature#43-Google-authentication
  .gitignore
  app.config.js
  eas.json
  metro.config.js
  package-lock.json
  package.json
  src/db/firebaseConfig.js
  src/views/Login.jsx
  src/views/MyFlights.jsx
  src/views/SignUp.jsx
Labels: @Zuack55

#50 Adding tests and static code analyzers to the project
  .gitignore
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/tests/components/Button.test.jsx
Labels: @Leonardo-Aguirre-Ponce
